In [1]:
import numpy as np

# THE BASICS

In [2]:
a = np.array([1,2,3])
print(a , "there the answer")

[1 2 3] there the answer


In [3]:
b = np.array([[9,8,7] , [6,5,4] , [3,2,1]])
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [4]:
# Dimension 
a.ndim

1

In [5]:
# Shape
b.shape

(3, 3)

In [6]:
 # type
a.dtype    

dtype('int64')

In [7]:
# size
a.itemsize

8

In [8]:
# total size .

a.nbytes

24

# Acessing/changing specific elemnts , rows , columns ,etc.

In [9]:
a = np.array([[1,2,3,4,5,16] , [6,7,8,9,10,17] , [11,12,13,14,15,18]] , dtype = "int32")
print(a)

[[ 1  2  3  4  5 16]
 [ 6  7  8  9 10 17]
 [11 12 13 14 15 18]]


In [10]:
#get a specific element [r , c].
a[0 , 3]

4

In [11]:
# get a specific row .
a[2 ,:]

array([11, 12, 13, 14, 15, 18], dtype=int32)

In [12]:
# get specific columns
a[:,4]

array([ 5, 10, 15], dtype=int32)

In [13]:
# getting Fancy [startingindex:endingindex:stepsize]
a[0,1:6:2]

array([ 2,  4, 16], dtype=int32)

In [14]:
## in row
a[2,3]=20
print(a)

[[ 1  2  3  4  5 16]
 [ 6  7  8  9 10 17]
 [11 12 13 20 15 18]]


In [15]:
## columns

a[:,3]=5
print(a)

[[ 1  2  3  5  5 16]
 [ 6  7  8  5 10 17]
 [11 12 13  5 15 18]]


#  3D examples

In [16]:
b = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print(b)                 

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [17]:
## get specific element ( work ouside in)

b[0,0,1]


2

In [18]:
## replacing 
b[:,1,:] = [[9,9] , [9,9]]
print(b)

[[[1 2]
  [9 9]]

 [[6 7]
  [9 9]]]


# Different types of arrays. 

In [19]:
## all zeros matrix
## same to matrix of 1's np.ones()
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
## any other numbers
np.full((2,3),20.1 , dtype = 'float32')

array([[20.1, 20.1, 20.1],
       [20.1, 20.1, 20.1]], dtype=float32)

In [21]:
## any pther number full_like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]], dtype=int32)

In [22]:
## random decimal numbers
np.random.rand(4,2)

array([[0.97149954, 0.09239865],
       [0.61836743, 0.16555519],
       [0.48276037, 0.1091792 ],
       [0.72894893, 0.36177947]])

In [23]:
##random integer value , here the 5 denotes that the numbers that will use to r=create random intergers numbers
np.random.randint(5, size=(3,3,5))

array([[[1, 3, 0, 4, 1],
        [3, 4, 0, 2, 4],
        [2, 0, 3, 0, 3]],

       [[4, 3, 3, 4, 4],
        [3, 1, 1, 2, 2],
        [3, 0, 2, 3, 0]],

       [[0, 0, 4, 4, 3],
        [4, 1, 1, 1, 4],
        [3, 0, 2, 1, 2]]])

In [24]:
## identity matrix 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
## Repeat the array
a1 = np.array([[[1,2,3,4] , [5,6,7,8]]])
r1 = np.repeat(a1,3,axis = 0)
print(r1)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [26]:
A = np.ones((5,5))
print (A)

B = np.zeros((3,3))
B[1,1] = 9
print(B)

A[1:4,1:4]= B
print(A)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
a = np.array([1,2,3])
b = a
b[0] = 200
b

array([200,   2,   3])

# Maths

In [28]:
## additon ,substraction , multiple , divide.
## a-2 , a/2 , a*2 and all thats stuff.
a = np.array([1,2,3,4] , dtype = 'float32') 
a

array([1., 2., 3., 4.], dtype=float32)

In [29]:
# a/2 
a*2

array([2., 4., 6., 8.], dtype=float32)

In [30]:
b = np.array([5,6,7,8] , dtype = 'float32') 
a+b

array([ 6.,  8., 10., 12.], dtype=float32)

In [31]:
## trignometry expression of "a" & "b"
#np.sin(a)
np.cos(b)

array([ 0.2836622 ,  0.96017027,  0.75390226, -0.14550003], dtype=float32)

# Linear Algebra

In [32]:
a = np.ones((2,4))
print(a)

b = np.full((4,2), 2)
print(b)

np.matmul(a,b)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[8., 8.],
       [8., 8.]])

In [33]:
### find the determinante.
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [34]:
S = np.array([[1,2,3,4,5,16] , [6,7,8,9,10,17] , [11,12,13,14,15,18]] , dtype = "int32")
S

array([[ 1,  2,  3,  4,  5, 16],
       [ 6,  7,  8,  9, 10, 17],
       [11, 12, 13, 14, 15, 18]], dtype=int32)

In [35]:
np.min(S)

1

In [36]:
np.max(S , axis = 1)

array([16, 17, 18], dtype=int32)

In [39]:
## some do with min, max, std.
##np.max(S)
np.sum(S)

171

# Reorganizing Arrays.

In [46]:
B = np.array([[1,2,3,4,5,16] , [6,7,8,9,10,17] , [11,12,13,14,15,18]] , dtype = "int32")
print(B)

A = B.reshape((6,3))
A

[[ 1  2  3  4  5 16]
 [ 6  7  8  9 10 17]
 [11 12 13 14 15 18]]


array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 6,  7,  8],
       [ 9, 10, 17],
       [11, 12, 13],
       [14, 15, 18]], dtype=int32)

In [47]:
## vrtically stocking vectors .
## horizontally --> np.hstack([A1,A2])
A1 = np.array([1,2,3,4])
A2 = np.array([5,6,7,8])

np.vstack([A1,A2,A1,A2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

# Load data direct in numpay arrays 

In [57]:
df = np.genfromtxt("/Users/randomchirag./Downloads/NumPy-master/data.txt" , delimiter = ",")
df = df.astype("int32")
print(df)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean masking and advance indexing

In [59]:
## read the file in bolean format.
df[df > 100]
df

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [60]:
((df > 50) & (df < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])